mockproject/mockporject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('superadmin/', include('superadmin.urls')),
    path('superadmin', RedirectView.as_view(url='/superadmin/')),
]

mockproject/superadmin/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from superadmin import views
app_name = 'superadmin'

urlpatterns = [
    path('',views.index.as_view(),name='login'),
    path('Dashboard',views.dashboard.as_view(),name='dashboard'),
    path('Logout', views.Logout.as_view(), name='Logout'),

    path('userlist', views.userlist.as_view(), name='userlist'),
    path('usercreate', views.usercreate.as_view(), name='usercreate'),

]

mockproject/superadmin/models.py
from django.db import models
# from django.contrib.postgres.fields import ArrayField
# from rest_framework import serializers
# from django.utils.text import slugify


from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)

# Create your models here.

GENDER_CHOICES = (
        ('1', 'Male'),
        ('2', 'Female'),
    )

USER_TYPE_CHOICES = (
      (1, 'superadmin'),
      (2, 'admin'),
      (3, 'user'),
  )

STATUS_CHOICES = (
      (1, 'unpaid'),
      (2, 'paid'),
      (3, 'cancelled'),
  )


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )
        user.admin = 2
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, email, password):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.admin = 3
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.admin = 1
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(max_length=255, blank=True, null=True,unique=True)
    password =  models.CharField(max_length=255, blank=True,null=True)
    user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES, default=1, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)
    is_active = models.BooleanField(default=True, blank=True, null=True)

    USERNAME_FIELD = 'email'

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.name


    def __str__(self):
        return self.name

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.admin

    @property
    def is_admin(self):
        "Is the user a admin member?"
        return self.admin





    objects = UserManager()


class Customers(models.Model):
    name = models.TextField(blank=True, null=True)
    phone = models.TextField(blank=True, null=True)
    email = models.TextField(blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

class Invoices(models.Model):
    customer = models.ForeignKey(Customers,blank=True, null=True, on_delete=models.CASCADE)
    amount = models.TextField(blank=True, null=True)
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES, default=1, blank=True, null=True)
    is_active = models.BooleanField(default=True, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

mockproject/superadmin/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse,JsonResponse
from superadmin.helper import renderhelper,is_ajax
from django.contrib.auth import login,logout, authenticate
from django.shortcuts import redirect
from superadmin.custom_permision import LoginRequiredMixin
from django.contrib.auth.hashers import check_password
from django.contrib import messages
from superadmin.models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import loader
from django.db.models import Q


# Create your views here.
class index(View):
    def get(self, request):
        context = {}
        return renderhelper(request, 'login', 'login',context)
    def post(self, request):
        context = {}
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(email=username, password=password)
        if user:
            login(request, user)
            return redirect('superadmin:dashboard')
        else:
            context['username'] = username
            context['password'] = password
            messages.info(request, 'Invalid Username or Password')
            return renderhelper(request, 'login', 'login',context)


class Logout(LoginRequiredMixin,View):
    def get(self, request):
        logout(request)
        return redirect('superadmin:login')


class dashboard(LoginRequiredMixin,View):
    def get(self, request):
        context = {}

        return renderhelper(request, 'home', 'index',context)



# User module start
class userlist(LoginRequiredMixin, View):
    def get(self, request,id=None):
        context = {}
        conditions = Q()

        if is_ajax(request):
            page = request.GET.get('page', 1)
            context['page'] = page
            status = request.GET.get('status')
            type = request.GET.get('type')
            if type == '1':
                id = request.GET.get('id')
                vl = request.GET.get('vl')
                cat = Customers.objects.get(id=id)
                if vl == '2':
                    cat.is_active = False
                else:
                    cat.is_active = True
                cat.save()
                messages.info(request, 'Successfully Updated')
            elif type == '2':
                id = request.GET.get('id')
                Customers.objects.filter(id=id).delete()
                messages.info(request, 'Successfully Deleted')
            if status:
                conditions &= Q(is_active=status)
            data_list = Customers.objects.filter(conditions).order_by('-id')
            paginator = Paginator(data_list, 15)

            try:
                datas = paginator.page(page)
            except PageNotAnInteger:
                datas = paginator.page(1)
            except EmptyPage:
                datas = paginator.page(paginator.num_pages)
            context['datas'] = datas
            template = loader.get_template('superadmin/user/user-table.html')
            html_content = template.render(context, request)
            return JsonResponse({'status': True, 'template': html_content})

        data = Customers.objects.all().order_by('-id')
        p = Paginator(data, 15)
        page_num = request.GET.get('page', 1)
        try:
            page = p.page(page_num)
        except EmptyPage:
            page = p.page(1)
        context['datas'] = page
        context['page'] = page_num
        return renderhelper(request, 'user', 'user-view', context)


class usercreate(LoginRequiredMixin, View):
    def get(self, request,id=None):
        context = {}
        try:
            context['data'] = Customers.objects.get(id=id)
        except:
            context['data'] = None
        return renderhelper(request, 'user', 'user-create', context)
    def post(self,request,id=None):
        try:
            data = Customers.objects.get(id=id)
            messages.info(request, 'Successfully Updated')
        except:
            data = Customers()
            messages.info(request, 'Successfully Added')

        eng_title = request.POST['eng_title']
        arb_title = request.POST['arb_title']
        data.eng_title = eng_title
        data.arb_title = arb_title
        data.save()
        return redirect('superadmin:userlist')

    # User module end

mockproject/templates/superadmin/user/user-create.html
{% include 'superadmin/layouts/header.html' %}
<!--app-content open-->
 <div class="main-content app-content mt-0">
     <div class="side-app">
         <!-- CONTAINER -->
         <div class="main-container container-fluid">
             <!-- PAGE-HEADER -->
             <div class="page-header">
                 <h1 class="page-title">Customers</h1>
                 <div>
                     <a class="btn btn-primary" href="{% url 'superadmin:userlist' %}"><i class="side-menu__icon fe fe-eye mx-1"></i>View All</a>
                 </div>
             </div>
             <!-- PAGE-HEADER END -->

             <!-- ROW OPEN -->
             <div class="row">
                 <div class="col-md-8 col-xl-8 col-12">
                     <div class="card">
                         <div class="card-body">
                             <form method="post">
                                 {% csrf_token %}
                                 <div class="row col-lg-12">
                                     <div class="form-group col-lg-6 col-12">
                                         <label for="" class="form-label"> Name</label>
                                         <input type="text" class="form-control" id="" placeholder="Name" name="eng_title" required value="{{data.eng_title}}">
                                     </div>
                                    <div class="form-group col-lg-6 col-12">
                                         <label for="" class="form-label"> Phone</label>
                                         <input type="text" class="form-control" id="" placeholder="Phone" name="arb_title" required value="{{data.arb_title}}">
                                     </div>
                                     <div class="form-group col-lg-6 col-12">
                                         <label for="" class="form-label"> E-mail</label>
                                         <input type="text" class="form-control" id="" placeholder="E-mail" name="arb_title" required value="{{data.arb_title}}">
                                     </div>
<div class="form-group col-lg-6 col-12">
                                         <label for="" class="form-label">Address</label>
                                         <input type="text" class="form-control" id="" placeholder="Address" name="arb_title" required value="{{data.arb_title}}">
                                     </div>

                                     <div class="form-group col-lg-12 col-12">
                                         <button type="submit" class="btn btn-primary mt-4 mb-0" id="submitButton">Submit</button>
                                         <a href="" class="btn btn-danger mt-4 mb-0">Cancel</a>
                                     </div>
                                 </div>
                             </form>
                         </div>
                     </div>
                     <!-- ROW CLOSED -->
                 </div>
                 <!-- CONTAINER END -->
             </div>
         </div>
     </div>
     <!--app-content close-->

{% include 'superadmin/layouts/footer.html' %}

mockproject/templates/superadmin/user/user-table.html
<input type="hidden" id="url" name="url" value="{{request.path}}">
<input type="hidden" id="page" name="page" value="{{page}}">
		 {% if messages %}
<div id="message_div" class="succs-msg">
    {% for message in messages %}
        <label class="form-group" style="">
            <p style="color:green;">{{message}}</p>
        </label>
    {% endfor %}
</div>
{% endif %}
<table class="table border-top table-bordered mb-0 table-hover">
                                    <thead>
                                        <tr>
                                            <th>Sl No</th>
                                            <th>title</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% if datas %}
                                        {% for i in datas %}
                                        <tr>
                                            <td>{{forloop.counter0|add:datas.start_index}}</td>
                                            <td>{{i.eng_title|upper}} / {{i.arb_title}}</td>
                                            <td>
                                               <div class="material-switch">
                                                     <input id="someSwitchOptionSuccess{{i.id}}" name="someSwitchOption001" type="checkbox" {% if i.is_active %}checked onclick="countrystatus({{i.id}},2)"{% else %}onclick="countrystatus({{i.id}},1)" {% endif %}  />
                                                     <label for="someSwitchOptionSuccess{{i.id}}" class="label-success"></label>
                                                 </div>
                                            </td>
                                            <td>

                                                <a class="btn btn-info btn-sm mb-1" href="{% url 'superadmin:countryedit' i.id %}"><i class="side-menu__icon fe fe-edit"></i></a>

                                                <a class="btn btn-danger btn-sm mb-1" href="javascript:void(0)" onclick="delete_modal({{i.id}})"><i class="side-menu__icon fe fe-trash" ></i></a>

                                            </td>
                                        </tr>
                                    {% endfor %}
                                    {% else %}
                                    <tr>
                                        <td colspan="4" align="center">
                                            No Data
                                        </td>
                                    </tr>
                                    {% endif %}

                                    </tbody>
                                </table>

<div class="card-body">

    Showing {{ datas.start_index }}-{{ datas.end_index }} of {{ datas.paginator.count }}
    {% if datas.has_other_pages %}
    <ul class="pagination">
        {% if datas.has_previous %}
        <li class="page-item page-prev">
            <a class="page-link" href="javascript:void(0)" onclick="return filtercountry('{{ datas.previous_page_number }}');" tabindex="-1">Prev</a>
        </li>
        {% else %}
        <li class="page-item page-prev">
            <span class="page-link"   tabindex="-1">Prev</span>
        </li>
          {% endif %}
         {% for i in datas.paginator.page_range %}
        {% if datas.number == i %}
        <li class="page-item active"><span class="page-link">
            {{ i }}</span><span class="sr-only">(current)</span></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="javascript:void(0)" onclick="return filtercountry('{{ i }}');">{{i}}</a></li>
          {% endif %}
        {% endfor %}
        {% if datas.has_next %}
        <li class="page-item page-next">
            <a class="page-link" href="javascript:void(0)" onclick="return filtercountry('{{ datas.next_page_number }}');">Next</a>
        </li>
         {% else %}
        <li class="page-item page-next"><span class="page-link">Next</span></li>
        {% endif %}
    </ul>
    {% endif %}
    <!-- pagination-wrapper -->
</div>

<script>
     $("#message_div").fadeOut(3000);
</script>

mockproject/templates/superadmin/user/user-view.html
{% include 'superadmin/layouts/header.html' %}
<!--app-content open-->
<div class="main-content app-content mt-0">
    <div class="side-app">

        <!-- CONTAINER -->
        <div class="main-container container-fluid">

            <!-- PAGE-HEADER -->
            <div class="page-header">
                <h1 class="page-title">Customers</h1>
                <div>
                    <a class="btn btn-primary" href="{% url 'superadmin:usercreate' %}"><i class="side-menu__icon fe fe-plus mx-1"></i>Add New</a>
                </div>
            </div>
            <!-- PAGE-HEADER END -->

            <!-- ROW OPEN -->
            <div class="row">
                <div class="col-xl-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">List Of All Customers</h3>
                        </div>
                        <div class="card-body">
                            <form>
                                <div class="row">
                                    <div class="form-group col-lg-2 col-12">
                                        <select name="country" id="status" class="form-control form-select select2" data-bs-placeholder="Select Country">
                                            <option value="">Select</option>
                                            <option value="True">Active</option>
                                            <option value="False">Inactive</option>

                                        </select>
                                    </div>
                                    <div class="form-group col-lg-3 col-12">
                                        <button class="btn btn-primary mr-1" type="button" onclick="filtercountry(1)">Search</button>
                                        <a class="btn btn-default" href="">Reset</a>
                                    </div>
                                </div>
                            </form>
                            <div class="table-responsive" >
                            {% include 'superadmin/user/user-table.html' %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ROW CLOSED -->



        </div>
        <!-- CONTAINER END -->
    </div>
</div>

<!--app-content close-->

<div class="modal  fade" id="smallmodal1" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">DESCRIPTION</h5>
                <button class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <table class="w-100">
                    <tr>
                        <td>
                            Which of the following elements are noble gases and have full electron shells? (Select all that apply)
                        </td>
                    </tr>
                </table>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" data-bs-dismiss="modal">Close</button>

            </div>
        </div>
    </div>
</div>


<div class="modal  fade" id="modaldemo5" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-md modal-dialog-centered text-center" role="document">
            <div class="modal-content ">

                <div class="modal-body">
                    <button aria-label="Close" class="btn-close position-absolute" data-bs-dismiss="modal">
					<span aria-hidden="true">&times;</span></button>
                    <i class="icon icon-close fs-70 text-danger lh-1 my-5 d-inline-block"></i>
                    <h4 class="text-danger">Are You Sure Do You Want To Delete ?</h4>
                    <p class="mg-b-20 mg-x-20">Item Will be Deleted Permanently</p>
                    <input type="hidden" id="hid" >
                    <button class="btn btn-success" onclick="countrydelete()">Yes</button>
					<button aria-label="Close" class="btn btn-danger pd-x-25" data-bs-dismiss="modal">Cancel</button>
                </div>
                <div class="modal-footer">


                </div>
            </div>
        </div>
    </div>

{% include 'superadmin/layouts/footer.html' %}