mockproject/mockporject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('superadmin/', include('superadmin.urls')),
    path('superadmin', RedirectView.as_view(url='/superadmin/')),
]

mockproject/superadmin/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from superadmin import views
app_name = 'superadmin'

urlpatterns = [
    path('',views.index.as_view(),name='login'),
    path('Dashboard',views.dashboard.as_view(),name='dashboard'),
    path('Logout', views.Logout.as_view(), name='Logout'),

    path('userlist', views.userlist.as_view(), name='userlist'),
    path('usercreate', views.usercreate.as_view(), name='usercreate'),

]

mockproject/superadmin/models.py
from django.db import models
# from django.contrib.postgres.fields import ArrayField
# from rest_framework import serializers
# from django.utils.text import slugify


from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)

# Create your models here.

GENDER_CHOICES = (
        ('1', 'Male'),
        ('2', 'Female'),
    )

USER_TYPE_CHOICES = (
      (1, 'superadmin'),
      (2, 'admin'),
      (3, 'user'),
  )

STATUS_CHOICES = (
      (1, 'unpaid'),
      (2, 'paid'),
      (3, 'cancelled'),
  )


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )
        user.admin = 2
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, email, password):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.admin = 3
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.admin = 1
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(max_length=255, blank=True, null=True,unique=True)
    password =  models.CharField(max_length=255, blank=True,null=True)
    user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES, default=1, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)
    is_active = models.BooleanField(default=True, blank=True, null=True)

    USERNAME_FIELD = 'email'

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.name


    def __str__(self):
        return self.name

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.admin

    @property
    def is_admin(self):
        "Is the user a admin member?"
        return self.admin





    objects = UserManager()


class Customers(models.Model):
    name = models.TextField(blank=True, null=True)
    phone = models.TextField(blank=True, null=True)
    email = models.TextField(blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

class Invoices(models.Model):
    customer = models.ForeignKey(Customers,blank=True, null=True, on_delete=models.CASCADE)
    amount = models.TextField(blank=True, null=True)
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES, default=1, blank=True, null=True)
    is_active = models.BooleanField(default=True, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

mockproject/superadmin/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse,JsonResponse
from superadmin.helper import renderhelper,is_ajax
from django.contrib.auth import login,logout, authenticate
from django.shortcuts import redirect
from superadmin.custom_permision import LoginRequiredMixin
from django.contrib.auth.hashers import check_password
from django.contrib import messages
from superadmin.models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import loader
from django.db.models import Q


# Create your views here.
class index(View):
    def get(self, request):
        context = {}
        return renderhelper(request, 'login', 'login',context)
    def post(self, request):
        context = {}
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(email=username, password=password)
        if user:
            login(request, user)
            return redirect('superadmin:dashboard')
        else:
            context['username'] = username
            context['password'] = password
            messages.info(request, 'Invalid Username or Password')
            return renderhelper(request, 'login', 'login',context)


class Logout(LoginRequiredMixin,View):
    def get(self, request):
        logout(request)
        return redirect('superadmin:login')


class dashboard(LoginRequiredMixin,View):
    def get(self, request):
        context = {}

        return renderhelper(request, 'home', 'index',context)



# User module start
class userlist(LoginRequiredMixin, View):
    def get(self, request,id=None):
        context = {}
        conditions = Q()

        if is_ajax(request):
            page = request.GET.get('page', 1)
            context['page'] = page
            status = request.GET.get('status')
            type = request.GET.get('type')
            if type == '1':
                id = request.GET.get('id')
                vl = request.GET.get('vl')
                cat = Customers.objects.get(id=id)
                if vl == '2':
                    cat.is_active = False
                else:
                    cat.is_active = True
                cat.save()
                messages.info(request, 'Successfully Updated')
            elif type == '2':
                id = request.GET.get('id')
                Customers.objects.filter(id=id).delete()
                messages.info(request, 'Successfully Deleted')
            if status:
                conditions &= Q(is_active=status)
            data_list = Customers.objects.filter(conditions).order_by('-id')
            paginator = Paginator(data_list, 15)

            try:
                datas = paginator.page(page)
            except PageNotAnInteger:
                datas = paginator.page(1)
            except EmptyPage:
                datas = paginator.page(paginator.num_pages)
            context['datas'] = datas
            template = loader.get_template('superadmin/user/user-table.html')
            html_content = template.render(context, request)
            return JsonResponse({'status': True, 'template': html_content})

        data = Customers.objects.all().order_by('-id')
        p = Paginator(data, 15)
        page_num = request.GET.get('page', 1)
        try:
            page = p.page(page_num)
        except EmptyPage:
            page = p.page(1)
        context['datas'] = page
        context['page'] = page_num
        return renderhelper(request, 'user', 'user-view', context)


class usercreate(LoginRequiredMixin, View):
    def get(self, request,id=None):
        context = {}
        try:
            context['data'] = Customers.objects.get(id=id)
        except:
            context['data'] = None
        return renderhelper(request, 'user', 'user-create', context)
    def post(self,request,id=None):
        try:
            data = Customers.objects.get(id=id)
            messages.info(request, 'Successfully Updated')
        except:
            data = Customers()
            messages.info(request, 'Successfully Added')

        eng_title = request.POST['eng_title']
        arb_title = request.POST['arb_title']
        data.eng_title = eng_title
        data.arb_title = arb_title
        data.save()
        return redirect('superadmin:userlist')

    # User module end

mockproject/templates/superadmin/layouts/footer.html
{% load static %}

        </div>



      

        <!-- FOOTER -->

        <footer class="footer">

            <div class="container">

                <div class="row align-items-center flex-row-reverse">

                    <div class="col-md-12 col-sm-12 text-center">

                        Copyright © <span id="year"></span> <a href="">Grocery Admin</a> All rights reserved.

                    </div>

                </div>

            </div>

        </footer>

        <!-- FOOTER END -->



    </div>



    <!-- BACK-TO-TOP -->

    <a href="#top" id="back-to-top"><i class="fa fa-angle-up"></i></a>



    <!-- JQUERY JS -->

    <script src="{% static 'superadmin/assets/js/jquery.min.js' %}"></script>



    <!-- BOOTSTRAP JS -->

    <script src="{% static 'superadmin/assets/plugins/bootstrap/js/popper.min.js' %}"></script>

    <script src="{% static 'superadmin/assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>

	

    <!-- SPARKLINE JS-->

    <script src="{% static 'superadmin/assets/js/jquery.sparkline.min.js' %}"></script>



    <!-- Sticky js -->

    <script src="{% static 'superadmin/assets/js/sticky.js' %}"></script>



    <!-- CHART-CIRCLE JS-->

   



   



    <!-- SIDEBAR JS -->

    <script src="{% static 'superadmin/assets/plugins/sidebar/sidebar.js' %}"></script>



   

   

    <!-- INTERNAL Flot JS -->

    <script src="{% static 'superadmin/assets/plugins/flot/jquery.flot.js' %}"></script>

    <script src="{% static 'superadmin/assets/plugins/flot/jquery.flot.fillbetween.js' %}"></script>

   <script src="{% static 'superadmin/assets/plugins/p-scroll/perfect-scrollbar.js' %}"></script>

    <script src="{% static 'superadmin/assets/plugins/p-scroll/pscroll.js' %}"></script>

    <script src="{% static 'superadmin/assets/plugins/p-scroll/pscroll-1.js' %}"></script>

    <script src="{% static 'superadmin/assets/plugins/flot/dashboard.sampledata.js' %}"></script>



    



    <!-- SIDE-MENU JS-->

    <script src="{% static 'superadmin/assets/plugins/sidemenu/sidemenu.js' %}"></script>

	

	<script src="{% static 'superadmin/assets/plugins/date-picker/date-picker.js' %}"></script>

    <script src="{% static 'superadmin/assets/plugins/date-picker/jquery-ui.js' %}"></script>

    <script src="{% static 'superadmin/assets/plugins/input-mask/jquery.maskedinput.js' %}"></script>

	

    <script src="{% static 'superadmin/assets/plugins/fileuploads/js/fileupload.js' %}"></script>

    <script src="{% static 'superadmin/assets/plugins/fileuploads/js/file-upload.js' %}"></script>

	

	<script src="{% static 'superadmin/assets/plugins/select2/select2.full.min.js' %}"></script>

    <script src="{% static 'superadmin/assets/js/select2.js' %}"></script>

	 <script src="{% static 'superadmin/assets/plugins/multipleselect/multiple-select.js' %}"></script>

    <script src="{% static 'superadmin/assets/plugins/multipleselect/multi-select.js' %}"></script>

    <!-- Color Theme js -->

    <script src="{% static 'superadmin/assets/js/themeColors.js' %}"></script>



    <!-- CUSTOM JS -->

    <script src="{% static 'superadmin/assets/js/custom.js' %}"></script>

   <script src="{% static 'superadmin/assets/plugins/summernote/summernote1.js' %}"></script>

    <script src="{% static 'superadmin/assets/js/summernote.js' %}"></script>

	  

 <script src="{% static 'superadmin/assets/plugins/gallery/picturefill.js' %}"></script>

    <script src="{% static 'superadmin/assets/plugins/gallery/lightgallery.js' %}"></script>

    <script src="{% static 'superadmin/assets/plugins/gallery/lightgallery-1.js' %}"></script>

    <script src="{% static 'superadmin/assets/plugins/gallery/lg-pager.js' %}"></script>

    <script src="{% static 'superadmin/assets/plugins/gallery/lg-autoplay.js' %}"></script>

    <script src="{% static 'superadmin/assets/plugins/gallery/lg-fullscreen.js' %}"></script>

    <script src="{% static 'superadmin/assets/plugins/gallery/lg-zoom.js' %}"></script>

    <script src="{% static 'superadmin/assets/plugins/gallery/lg-hash.js' %}"></script>

    <script src="{% static 'superadmin/assets/plugins/gallery/lg-share.js' %}"></script>

	<script src="{% static 'superadmin/assets/js/formelementadvnced.js' %}"></script>

    <script src="{% static 'superadmin/assets/js/form-elements.js' %}"></script>

	

    <script src="{% static 'superadmin/assets/js/custom-js-new.js' %}"></script>

	 

	<script src="{% static 'superadmin/assets/plugins/time-picker/jquery.timepicker.js' %}"></script>

    <script src="{% static 'superadmin/assets/plugins/time-picker/toggles.min.js' %}"></script>

	<script src="{% static 'superadmin/assets/js/show-password.min.js' %}"></script>
	<script src="{% static 'superadmin/assets/plugins/bootstrap-daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'superadmin/assets/plugins/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
    <script src="{% static 'superadmin/assets/js/formelementadvnced.js' %}"></script>
    <script src="{% static 'superadmin/assets/js/form-elements.js' %}"></script>
    <script src="{% static 'superadmin/custom/custom.js' %}"></script>

    <script src="{% static 'superadmin/assets/plugins/notify/js/rainbow.js' %}"></script>
    <script src="{% static 'superadmin/assets/plugins/notify/js/sample.js' %}"></script>
    <script src="{% static 'superadmin/assets/plugins/notify/js/notifIt.js' %}"></script>

<script>

function not1() {
    notif({
        msg: "<b>Success:</b> Content Updated Successfully",
        type: "success"
    });
}

function not2() {
    notif({
        msg: "<b>Oops!</b> An Error Occurred",
        type: "error",
        position: "center"
    });
}

 $('.fc-datepicker').datepicker({
        showOtherMonths: false,
        selectOtherMonths: false
    });

</script>

</body>



</html>

mockproject/templates/superadmin/layouts/header.html
{% load static %}
<!doctype html>
<html lang="en" dir="ltr">

<head>
  <!-- META DATA -->
  <meta charset="UTF-8">
  <meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=0'>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- FAVICON -->
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'superadmin/assets/images_ex/icon.png' %}" />
  <!-- TITLE -->
  <title>GROCERY Admin | Dashboard</title>
  <!-- BOOTSTRAP CSS -->
  <link id="style" href="{% static 'superadmin/assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
  <!-- STYLE CSS -->
  <link href="{% static 'superadmin/assets/css/style.css' %}" rel="stylesheet" />
  <link href="{% static 'superadmin/assets/css/dark-style.css' %}" rel="stylesheet" />
  <link href="{% static 'superadmin/assets/css/transparent-style.css' %}" rel="stylesheet">
  <link href="{% static 'superadmin/assets/css/skin-modes.css' %}" rel="stylesheet" />
  <link href="{% static 'superadmin/assets/css/style-custom.css' %}" rel="stylesheet" />
  <!--- FONT-ICONS CSS -->
  <link href="{% static 'superadmin/assets/css/icons.css' %}" rel="stylesheet" />
  <!-- COLOR SKIN CSS -->
  <link id="theme" rel="stylesheet" type="text/css" media="all" href="{% static 'superadmin/assets/colors/color1.css' %}" />
</head>

<body class="app sidebar-mini ltr light-mode">
  <!-- PAGE -->
  <div class="page">
    <div class="page-main">
      <!-- app-Header -->
      <div class="app-header header sticky">
        <div class="container-fluid main-container">
          <div class="d-flex">
            <a aria-label="Hide Sidebar" class="app-sidebar__toggle" data-bs-toggle="sidebar" href="javascript:void(0)"></a>
            <!-- sidebar-toggle-->
            <a class="logo-horizontal " href="{% url 'superadmin:dashboard' %}">
              <img src="{% static 'superadmin/assets/images_ex/logo-light.png' %}" class="header-brand-img desktop-logo' %}" alt="logo">
              <img src="{% static 'superadmin/assets/images_ex/logo.png' %}" class="header-brand-img light-logo1' %}" alt="logo">
            </a>
            <div class="d-flex order-lg-2 ms-auto header-right-icons">
              <div class="d-flex country">
                <a class="nav-link icon theme-layout nav-link-bg layout-setting">
                  <span class="dark-layout">
                    <i class="fe fe-moon"></i>
                  </span>
                  <span class="light-layout">
                    <i class="fe fe-sun"></i>
                  </span>
                </a>
              </div>
              <div class="dropdown d-flex profile-1">
                <a href="javascript:void(0)" data-bs-toggle="dropdown" class="nav-link leading-none d-flex">
                  <img src="{% static 'superadmin/assets/images_ex/user.png' %}" alt="profile-user" class="avatar  profile-user brround cover-image">
                </a>
                <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                  <div class="drop-heading">
                    <div class="text-center">
                      <h5 class="text-dark mb-0 fs-14 fw-semibold">Username</h5>
                      <small class="text-muted">Admin</small>
                    </div>
                  </div>
                  <div class="dropdown-divider m-0"></div>

                  <a class="dropdown-item" href="{% url 'superadmin:Logout' %}">
                    <i class="dropdown-icon fe fe-alert-circle"></i> Sign out </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /app-Header -->
      <!--APP-SIDEBAR-->
      <div class="sticky">
        <div class="app-sidebar__overlay" data-bs-toggle="sidebar"></div>
        <div class="app-sidebar">
          <div class="side-header">
            <a class="header-brand1" href="{% url 'superadmin:dashboard' %}">
              <img src="{% static 'superadmin/assets/images_ex/logo-light.png' %}" class="header-brand-img desktop-logo" alt="logo">
              <img src="{% static 'superadmin/assets/images_ex/icon.png' %}" class="header-brand-img toggle-logo" alt="logo">
              <img src="{% static 'superadmin/assets/images_ex/icon.png' %}" class="header-brand-img light-logo" alt="logo">
              <img src="{% static 'superadmin/assets/images_ex/logo.png' %}" class="header-brand-img light-logo1" alt="logo">
            </a>
            <!-- LOGO -->
          </div>
          <div class="main-sidemenu">
            <div class="slide-left disabled" id="slide-left">
              <svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191" width="24" height="24" viewBox="0 0 24 24">
                <path d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z" />
              </svg>
            </div>
            <ul class="side-menu">
              <li class="sub-category">
                <h3>Main</h3>
              </li>
              <li class="slide">
                <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url 'superadmin:dashboard' %}">
                  <i class="side-menu__icon fe fe-home"></i>
                  <span class="side-menu__label">Dashboard</span>
                </a>
              </li>

              <li class="slide">
                <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url 'superadmin:userlist' %}">
                  <i class="side-menu__icon fe fe-user"></i>
                  <span class="side-menu__label">Customer</span>
                </a>
              </li>
              <li class="slide">
                <a class="side-menu__item has-link" data-bs-toggle="slide" href="reports-view.php">
                  <i class="side-menu__icon fe fe-user"></i>
                  <span class="side-menu__label">Invoice</span>
                </a>
              </li>
            </ul>
            <div class="slide-right" id="slide-right">
              <svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191" width="24" height="24" viewBox="0 0 24 24">
                <path d="M10.707 17.707 16.414 12l-5.707-5.707-1.414 1.414L13.586 12l-4.293 4.293z" />
              </svg>
            </div>
          </div>
        </div>
        <!--/APP-SIDEBAR-->
      </div>